### ISSUE TITLE
Secure ngx-launcher release process (and update) doc

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/ngx-launcher#261]
In order to make this repository release process automatic and secured:
- Only ngx-launcher admins and CI user must be allowed on the ngx-launch npm account
- npm release must be only done by CI
- Doc must be updated

**Comment by ia3andy** [comment]
@gastaldi it seems the job is using git tags to choose the next npm version but the process it is not tagging the repository at the end of the job https://ci.centos.org/view/Devtools/job/devtools-ngx-launcher-npm-publish-build-master/

**Comment by gastaldi** [comment]
Just for posterity, there are three problems with the current job approach

1) People are running npm publish locally. This is bad because they are not pushing changes to master and we have no idea what the version contains

2) There is no way to bump the minor version with the current approach

3) A version release could contain more commits but the current approach doesn't allow that

**Comment by jyasveer** [comment]
There is a open issue with this process which i had raised earlier https://github.com/openshiftio/openshift.io/issues/3585

**Comment by gastaldi** [comment]
We could consider using [prerelease tags](https://docs.npmjs.com/misc/semver#prerelease-tags) for development releases. This could be performed automatically on each master push and then when a fixed version when a tag is created. 

Also (in another topic)  maybe we should consider renaming the project to `ngx-launcher`?

**Comment by ia3andy** [comment]
Fixed by https://github.com/fabric8-launcher/ngx-launcher/issues/324
